export const LOAD_IMAGE_HEADER = 'LOAD_IMAGE_HEADER';
export const LOAD_IMAGES_MAIN = 'LOAD_IMAGES_CONTAINER';
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const LOAD_IMAGE_SEARCH = 'LOAD_IMAGE_SEARCH';
export const LOAD_IMAGE_SEARCH_PAGINATION = 'LOAD_IMAGE_SEARCH_PAGINATION';
